export const chatStrings = {
  header: {
    botNameDefault: '9xen AI Advisor',
    botTitleDefault: 'Neural Gateway Active',
    versionBadge: 'v2.6 Pro',
    fullScreen: 'Full Screen',
    exitFullScreen: 'Exit Full Screen',
    recentConversations: 'Recent Conversations',
    exportChat: 'Export Chat History',
    systemSettings: 'AI System Settings',
    clearSession: 'Clear Conversation',
    closeWidget: 'Close Assistant',
  },
  composer: {
    placeholder: 'Ask about 9xen Core, Reguletter, Quant Engine, or fine-tuning...',
    send: 'Send Message',
    stopGenerating: 'Stop Generating',
    startVoice: 'Voice Input',
    stopVoice: 'Listening...',
    attachFile: 'Attach Spec Sheet or Screenshot',
    uploadingFile: 'Uploading attachment...',
    shortcutTip: 'Press Enter to send, Shift+Enter for new line',
  },
  sessionSidebar: {
    title: 'Consultation Sessions',
    searchPlaceholder: 'Search conversations...',
    newChat: 'New Consultation',
    pinnedSection: 'Pinned Sessions',
    recentSection: 'Recent Consultations',
    noSessionsFound: 'No matching conversations found.',
    clearAll: 'Clear All Sessions',
    keyboardShortcuts: 'Keyboard Shortcuts',
  },
  actions: {
    copyText: 'Copy Text',
    copied: 'Copied!',
    editMessage: 'Edit Message',
    regenerate: 'Regenerate Response',
    helpful: 'Helpful',
    unhelpful: 'Not Helpful',
    sourcesAndReferences: 'Verified Knowledge Sources',
    humanHandoffNotice: 'Executive Lead Sync Active: A 9xen Solutions Architect has been alerted for priority review.',
  },
  settings: {
    modalTitle: 'Neural Model & Systemic Parameters',
    modelLabel: 'Target Model Cluster',
    personaLabel: 'Architect Persona',
    knowledgeModeLabel: 'Enterprise RAG Grounding',
    temperatureLabel: 'Creativity / Temperature',
    saveSettings: 'Apply Configurations',
  },
  export: {
    exportJson: 'Export JSON (.json)',
    exportTxt: 'Export Text File (.txt)',
    exportMd: 'Export Markdown (.md)',
    exportPdf: 'Export / Print PDF',
  },
  shortcuts: {
    title: 'Keyboard Shortcuts',
    toggleWidget: 'Toggle Assistant Widget',
    newChat: 'Start New Consultation',
    closeWidget: 'Close Window / Cancel',
    shortcutsHelp: 'Open Shortcuts Menu',
  },
  defaultFollowUps: [
    'Overview of all 9xen Products & Services',
    'How does 9xen Agentic Core orchestrate workflows?',
    'What are the compliance capabilities of Reguletter?',
    'How does the Quant Trading Engine enforce 4% max drawdown?',
  ],
  welcomeFallback:
    'Welcome to 9xen. I am your Enterprise Solutions & AI Systems Advisor.\n\nHow can I help you across our portfolio today? Ask me about **9xen Agentic Core**, **Reguletter Compliance SaaS**, **Custom LLM Fine-Tuning**, **Real Estate AI**, or our **Institutional Quant Trading Engine (AlphaBot Pro)**.',
};
